# Generated by Django 3.1.4 on 2020-12-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barrios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cervecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerveceraname', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
